### ISSUE TITLE
out of date - new version is in another repo

### ISSUE THREAD

**Issue by justanothergithubuserNr2** [flathub/org.midori_browser.Midori#23]
The latest update of  https://github.com/midori-browser is from 2019 (see https://github.com/midori-browser/core/releases/tag/v9.0).
For a security relevant software like a web browser, it seems to be a very bad idea to ship an 5 years outdated version.

It seems like a [company named "Astian"](https://astian.org/) [is](https://de.wikipedia.org/wiki/Midori_(Browser))  [continuing](https://github.com/midori-browser/core/issues/468)   [development](https://astian.org/midori-browser/): https://github.com/goastian/midori-desktop

Could you update this package, please?

**Comment by bbhtt** [comment]
That's a whole different browser and it needs to be submitted separately by someone.

It was based on Electron, then chromium and now based on Firefox.

This one is based on Webkitgtk.

**Comment by Ponchale** [comment]
> That's a whole different browser and it needs to be submitted separately by someone.
> 
> It was based on Electron, then chromium and now based on Firefox.
> 
> This one is based on Webkitgtk.

We are looking for the best alternative for the market, that's why our evaluation process, even though it uses WebKit we recommend everyone to migrate to the new version.
